/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warunginspirasi;

import javax.swing.ImageIcon;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Anas.A
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */ 
    
   protected static String admin1 = "Anas";
   protected static String admin2 = "Seno";
   protected static String Pass_admin = "admin123";
   String[] nama = new String[1];
   ArrayList ar = new ArrayList();

    public FormLogin() {
        initComponents();
        
    }
    
    
   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formLogin = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JLabel();
        password = new javax.swing.JLabel();

        setUndecorated(true);

        formLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        formLogin.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 40));

        txtPass.setBackground(new java.awt.Color(253, 228, 168));
        txtPass.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(204, 153, 0));
        txtPass.setBorder(null);
        formLogin.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, 30));

        txtUser.setBackground(new java.awt.Color(253, 228, 168));
        txtUser.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(204, 153, 0));
        txtUser.setBorder(null);
        formLogin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 190, 20));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login.png"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoginMouseReleased(evt);
            }
        });
        formLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/login.png"))); // NOI18N
        formLogin.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        WarungSolo a = new WarungSolo();
        a.setVisible(true);
        this.dispose();
        a.dispose();
    }//GEN-LAST:event_usernameMouseClicked

// Tombol Login
    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        ImageIcon lg = new ImageIcon(getClass().getResource("/icon/loginputih.png"));
        btnLogin.setIcon(lg);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        ImageIcon lg = new ImageIcon(getClass().getResource("/icon/login.png"));
        btnLogin.setIcon(lg);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
        ImageIcon lg = new ImageIcon(getClass().getResource("/icon/loginhitam.png"));
        btnLogin.setIcon(lg);
    }//GEN-LAST:event_btnLoginMousePressed

    private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
        ImageIcon lg = new ImageIcon(getClass().getResource("/icon/loginputih.png"));
        btnLogin.setIcon(lg);
    }//GEN-LAST:event_btnLoginMouseReleased

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        
//        MenuAdmin adm = new MenuAdmin();
        WarungSolo ws = new WarungSolo();
//        DefaultTableModel md = (DefaultTableModel) ws.hasilKritikSaran.getModel();
//        md.addRow(new Object[]{ namaCadangan,kritikSaranCadangan});
        ws.btnHasilJualan.setVisible(true);
        ws.btnReservasi.setVisible(true);
        ws.btnMenu.setVisible(true);
        ws.btnSaranKritik.setVisible(true);
        ws.btnPembayaran.setVisible(true);
        
            if(admin1.equalsIgnoreCase(txtUser.getText()) && Pass_admin.equalsIgnoreCase(txtPass.getText())) {
               
                this.setVisible(false);
                ws.setVisible(true);
                txtUser.setText(""); txtPass.setText("");
                JOptionPane.showMessageDialog(null, "Anda berhasil login");
                ws.Ucapan.setText("Selamat Datang"+" "+ admin1);
                ws.Ucapan.setVisible(true);
                
                
            }else if(admin2.equalsIgnoreCase(txtUser.getText()) && Pass_admin.equalsIgnoreCase(txtPass.getText())){
             ;
                this.setVisible(false);
                ws.setVisible(true);
                txtUser.setText(""); txtPass.setText("");
                JOptionPane.showMessageDialog(null, "Anda berhasil login");
                ws.Ucapan.setText("Selamat Datang"+" "+ admin2);
                ws.Ucapan.setVisible(true);
            }else{
                this.setVisible(true);
                JOptionPane.showMessageDialog(null, "Input gagal coba masukan lagi");
                txtUser.setText(""); txtPass.setText("");
            }
            
        
            
    }//GEN-LAST:event_btnLoginMouseClicked


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel btnLogin;
    private javax.swing.JPanel formLogin;
    private javax.swing.JLabel password;
    public javax.swing.JPasswordField txtPass;
    public javax.swing.JTextField txtUser;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
