/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warunginspirasi;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Anas.A
 */
public class FormReservasi extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormReservasi
     */
    public FormReservasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Namarev = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        Norev = new javax.swing.JLabel();
        btnOkerev = new javax.swing.JLabel();
        btnPindah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Namarev.setBackground(new java.awt.Color(234, 234, 234));
        Namarev.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        Namarev.setBorder(null);
        jPanel1.add(Namarev, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 260, 40));

        btn1.setBackground(new java.awt.Color(0, 204, 51));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.setToolTipText("");
        btn1.setActionCommand("");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, 90));

        btn2.setBackground(new java.awt.Color(0, 204, 51));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, 90));

        btn3.setBackground(new java.awt.Color(0, 204, 51));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 140, 90));

        btn4.setBackground(new java.awt.Color(0, 204, 51));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 140, 90));

        btn5.setBackground(new java.awt.Color(0, 204, 51));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 130, 90));

        btn6.setBackground(new java.awt.Color(0, 204, 51));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 120, 90));

        btn7.setBackground(new java.awt.Color(0, 204, 51));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 130, 90));

        btn8.setBackground(new java.awt.Color(0, 204, 51));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 140, 90));

        btn9.setBackground(new java.awt.Color(0, 204, 51));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 140, 90));

        btn10.setBackground(new java.awt.Color(0, 204, 51));
        btn10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn10.setText("10");
        btn10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 130, 90));

        btn11.setBackground(new java.awt.Color(0, 204, 51));
        btn11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn11.setText("11");
        btn11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel1.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 120, 90));

        btn12.setBackground(new java.awt.Color(0, 204, 51));
        btn12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn12.setText("12");
        btn12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel1.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 130, 90));

        btn13.setBackground(new java.awt.Color(0, 204, 51));
        btn13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn13.setText("13");
        btn13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        jPanel1.add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 140, 90));

        btn14.setBackground(new java.awt.Color(0, 204, 51));
        btn14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn14.setText("14");
        btn14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        jPanel1.add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 140, 90));

        btn15.setBackground(new java.awt.Color(0, 204, 51));
        btn15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn15.setText("15");
        btn15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        jPanel1.add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 130, 90));

        Norev.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jPanel1.add(Norev, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 70, 40));

        btnOkerev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ok.png"))); // NOI18N
        btnOkerev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkerevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOkerevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOkerevMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOkerevMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOkerevMouseReleased(evt);
            }
        });
        jPanel1.add(btnOkerev, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        btnPindah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPindah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pindah.png"))); // NOI18N
        btnPindah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPindahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPindahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPindahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPindahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPindahMouseReleased(evt);
            }
        });
        jPanel1.add(btnPindah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/reservasiNew.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
//tombol oke
    private void btnOkerevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMouseEntered
        ImageIcon bo = new ImageIcon(getClass().getResource("/icon/okputih.png"));
        btnOkerev.setIcon(bo);
    }//GEN-LAST:event_btnOkerevMouseEntered

    private void btnOkerevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMouseExited
        ImageIcon bo = new ImageIcon(getClass().getResource("/icon/ok.png"));
        btnOkerev.setIcon(bo);
    }//GEN-LAST:event_btnOkerevMouseExited

    private void btnOkerevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMousePressed
        ImageIcon bo = new ImageIcon(getClass().getResource("/icon/okhitam.png"));
        btnOkerev.setIcon(bo);
    }//GEN-LAST:event_btnOkerevMousePressed

    private void btnOkerevMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMouseReleased
        ImageIcon bo = new ImageIcon(getClass().getResource("/icon/okputih.png"));
        btnOkerev.setIcon(bo);
    }//GEN-LAST:event_btnOkerevMouseReleased
   
   
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        Norev.setText("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        Norev.setText("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        Norev.setText("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        Norev.setText("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        Norev.setText("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        Norev.setText("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        Norev.setText("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        Norev.setText("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        Norev.setText("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        Norev.setText("10");
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        Norev.setText("11");
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        Norev.setText("12");
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        Norev.setText("13");
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        Norev.setText("14");
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        Norev.setText("15");
    }//GEN-LAST:event_btn15ActionPerformed

    
    
// Ini kodenya misah dari grup button karena sya lupa menaruh 
    private void btnOkerevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMouseClicked
        
        String a = Namarev.getText();
        Namarev.setText(a);
        
        if(Namarev.getText().isEmpty() && Norev.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama dan Reservasi harus diisi");
        }else if(Namarev.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong");
        }else if(Norev.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nomor Reservasi tidak boleh kosong");
        }else if(Norev.getText().equalsIgnoreCase("1")) {
            btn1.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("2")){
            btn2.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("3")){
            btn3.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("4")){
            btn4.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("5")){
            btn5.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("6")){
            btn6.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("7")){
            btn7.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("8")){
            btn8.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("9")){
            btn9.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("10")){
            btn10.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("11")){
            btn11.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("12")){
            btn12.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("13")){
            btn13.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("14")){
            btn14.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("15")){
            btn15.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }
    }//GEN-LAST:event_btnOkerevMouseClicked

    
 //button pindah
    private void btnPindahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMouseClicked
//        TampilanAwal tw = new TampilanAwal(); 
        Pindah pd = new Pindah();
        pd.setVisible(true);
        this.setVisible(false);

        String b = Norev.getText();
        pd.krsAwal.setText(b);
        String a = Namarev.getText();
//        pd.Namacadangan.setText(a);
//        pd.Namacadangan.hide();

        if(Norev.getText().equalsIgnoreCase("1")) {
            pd.btnPindah1.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("2")) {
            pd.btnPindah2.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("3")) {
            pd.btnPindah3.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("4")) {
            pd.btnPindah4.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("5")) {
            pd.btnPindah5.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("6")) {
            pd.btnPindah6.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("7")) {
            pd.btnPindah7.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("8")) {
            pd.btnPindah8.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("9")) {
            pd.btnPindah9.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("10")) {
            pd.btnPindah10.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("11")) {
            pd.btnPindah11.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("12")) {
            pd.btnPindah12.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("13")) {
            pd.btnPindah13.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("14")) {
            pd.btnPindah14.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("15")) {
            pd.btnPindah15.setBackground(new java.awt.Color(247, 252, 26));
        }

    }//GEN-LAST:event_btnPindahMouseClicked

    private void btnPindahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMouseEntered
        ImageIcon bp = new ImageIcon(getClass().getResource("/icon/pindahputih.png"));
        btnPindah.setIcon(bp);
    }//GEN-LAST:event_btnPindahMouseEntered

    private void btnPindahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMouseExited
        ImageIcon bp = new ImageIcon(getClass().getResource("/icon/pindah.png"));
        btnPindah.setIcon(bp);
    }//GEN-LAST:event_btnPindahMouseExited

    private void btnPindahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMousePressed
        ImageIcon bp = new ImageIcon(getClass().getResource("/icon/pindahhitam.png"));
        btnPindah.setIcon(bp);
    }//GEN-LAST:event_btnPindahMousePressed

    private void btnPindahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMouseReleased
        ImageIcon bp = new ImageIcon(getClass().getResource("/icon/pindahputih.png"));
        btnPindah.setIcon(bp);
    }//GEN-LAST:event_btnPindahMouseReleased



    
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Namarev;
    public javax.swing.JLabel Norev;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn10;
    public javax.swing.JButton btn11;
    public javax.swing.JButton btn12;
    public javax.swing.JButton btn13;
    public javax.swing.JButton btn14;
    public javax.swing.JButton btn15;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    private javax.swing.JLabel btnOkerev;
    private javax.swing.JLabel btnPindah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
