/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warunginspirasi;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Anas.A
 */
public class Pindah extends javax.swing.JFrame {

    /**
     * Creates new form Pindah
     */
    public Pindah() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        cadangan.setVisible(true);
        Namacadangan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPindah11 = new javax.swing.JButton();
        btnPindah12 = new javax.swing.JButton();
        btnPindah13 = new javax.swing.JButton();
        btnPindah14 = new javax.swing.JButton();
        btnPindah15 = new javax.swing.JButton();
        btnPindah6 = new javax.swing.JButton();
        btnPindah7 = new javax.swing.JButton();
        btnPindah8 = new javax.swing.JButton();
        btnPindah9 = new javax.swing.JButton();
        btnPindah10 = new javax.swing.JButton();
        btnPindah1 = new javax.swing.JButton();
        btnPindah2 = new javax.swing.JButton();
        btnPindah3 = new javax.swing.JButton();
        btnPindah4 = new javax.swing.JButton();
        btnPindah5 = new javax.swing.JButton();
        awal = new javax.swing.JLabel();
        pindah = new javax.swing.JLabel();
        krsAwal = new javax.swing.JLabel();
        krsSekarang = new javax.swing.JLabel();
        Okepindah = new javax.swing.JButton();
        Closerev = new javax.swing.JLabel();
        Namacadangan = new javax.swing.JLabel();
        cadangan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setUndecorated(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPindah11.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah11.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah11.setText("11");
        btnPindah11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah11ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, 70));

        btnPindah12.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah12.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah12.setText("12");
        btnPindah12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah12ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 70, 70));

        btnPindah13.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah13.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah13.setText("13");
        btnPindah13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah13ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 70, 70));

        btnPindah14.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah14.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah14.setText("14");
        btnPindah14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah14ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 70, 70));

        btnPindah15.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah15.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah15.setText("15");
        btnPindah15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah15ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 70, 70));

        btnPindah6.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah6.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah6.setText("6");
        btnPindah6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah6ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 70));

        btnPindah7.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah7.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah7.setText("7");
        btnPindah7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah7ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 70, 70));

        btnPindah8.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah8.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah8.setText("8");
        btnPindah8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah8ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 70, 70));

        btnPindah9.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah9.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah9.setText("9");
        btnPindah9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah9ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 70, 70));

        btnPindah10.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah10.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah10.setText("10");
        btnPindah10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah10ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 70, 70));

        btnPindah1.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah1.setText("1");
        btnPindah1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 70));

        btnPindah2.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah2.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah2.setText("2");
        btnPindah2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 70));

        btnPindah3.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah3.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah3.setText("3");
        btnPindah3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 70, 70));

        btnPindah4.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah4.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah4.setText("4");
        btnPindah4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 70, 70));

        btnPindah5.setBackground(new java.awt.Color(0, 204, 51));
        btnPindah5.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        btnPindah5.setText("5");
        btnPindah5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPindah5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindah5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPindah5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 70, 70));

        awal.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        awal.setText("Kursi saat ini    :");
        jPanel2.add(awal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        pindah.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        pindah.setText("Kursi sekarang  :");
        jPanel2.add(pindah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        krsAwal.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jPanel2.add(krsAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 60, 30));

        krsSekarang.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jPanel2.add(krsSekarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 60, 30));

        Okepindah.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        Okepindah.setText("Oke");
        Okepindah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Okepindah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkepindahActionPerformed(evt);
            }
        });
        jPanel2.add(Okepindah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, 30));

        Closerev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        Closerev.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                CloserevComponentAdded(evt);
            }
        });
        Closerev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloserevMouseClicked(evt);
            }
        });
        jPanel2.add(Closerev, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 40));
        jPanel2.add(Namacadangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 114, 70, 30));
        jPanel2.add(cadangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/loginblank.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
// Button pada Jframe Pindah.java
    private void btnPindah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah1ActionPerformed
        krsSekarang.setText("1"); 
    }//GEN-LAST:event_btnPindah1ActionPerformed

    private void btnPindah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah2ActionPerformed
        krsSekarang.setText("2"); 
    }//GEN-LAST:event_btnPindah2ActionPerformed

    private void btnPindah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah3ActionPerformed
        krsSekarang.setText("3"); 
    }//GEN-LAST:event_btnPindah3ActionPerformed

    private void btnPindah4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah4ActionPerformed
        krsSekarang.setText("4"); 
    }//GEN-LAST:event_btnPindah4ActionPerformed

    private void btnPindah5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah5ActionPerformed
        krsSekarang.setText("5"); 
    }//GEN-LAST:event_btnPindah5ActionPerformed

    private void btnPindah6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah6ActionPerformed
        krsSekarang.setText("6"); 
    }//GEN-LAST:event_btnPindah6ActionPerformed

    private void btnPindah7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah7ActionPerformed
        krsSekarang.setText("7"); 
    }//GEN-LAST:event_btnPindah7ActionPerformed

    private void btnPindah8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah8ActionPerformed
        krsSekarang.setText("8"); 
    }//GEN-LAST:event_btnPindah8ActionPerformed

    private void btnPindah9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah9ActionPerformed
        krsSekarang.setText("9"); 
    }//GEN-LAST:event_btnPindah9ActionPerformed

    private void btnPindah10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah10ActionPerformed
       krsSekarang.setText("10"); 
    }//GEN-LAST:event_btnPindah10ActionPerformed

    private void btnPindah11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah11ActionPerformed
        krsSekarang.setText("11"); 
    }//GEN-LAST:event_btnPindah11ActionPerformed

    private void btnPindah12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah12ActionPerformed
        krsSekarang.setText("12"); 
    }//GEN-LAST:event_btnPindah12ActionPerformed

    private void btnPindah13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah13ActionPerformed
        krsSekarang.setText("13"); 
    }//GEN-LAST:event_btnPindah13ActionPerformed

    private void btnPindah14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah14ActionPerformed
        krsSekarang.setText("14"); 
    }//GEN-LAST:event_btnPindah14ActionPerformed

    private void btnPindah15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindah15ActionPerformed
        krsSekarang.setText("15"); 
    }//GEN-LAST:event_btnPindah15ActionPerformed

    
//Button oke di Jframe Pindah.java
    private void OkepindahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkepindahActionPerformed
        WarungSolo tw = new WarungSolo();
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin pindah kursi ?", "Pindah kursi", JOptionPane.YES_NO_OPTION);
        FormLogin fl = new FormLogin();
        tw.btnHasilJualan.setVisible(true);
        
//        if(fl.txtUser.getText().equals(fl.admin1)){
//            tw.Ucapan.setText("Selamat Datang"+" "+ fl.admin1);
//            tw.Ucapan.setVisible(true);
//        }else if(fl.txtUser.getText().equals(fl.admin2)){
//            tw.Ucapan.setText("Selamat Datang"+" "+ fl.admin2);
//            tw.Ucapan.setVisible(true);
//        }
        
        if(konfirmasi==JOptionPane.YES_OPTION) {
//             tw.UcapanCadangan.setText(cadangan.getText());
//             tw.UcapanCadangan.setVisible(true);
             tw.namaPemesan.setText(Namacadangan.getText());
             
            //Untuk set warna hijau di menu Reservasi pada TampilanAwal.java
            if(krsAwal.getText().equals("1")){
                tw.btn1.setBackground(new java.awt.Color(0,204,51));
                btnPindah1.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("2")){
                tw.btn2.setBackground(new java.awt.Color(0,204,51));
                btnPindah2.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("3")){
                tw.btn3.setBackground(new java.awt.Color(0,204,51));
                btnPindah3.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("4")){
                tw.btn4.setBackground(new java.awt.Color(0,204,51));
                btnPindah4.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("5")){
                tw.btn5.setBackground(new java.awt.Color(0,204,51));
                btnPindah5.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("6")){
                tw.btn6.setBackground(new java.awt.Color(0,204,51));
                btnPindah6.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("7")){
                tw.btn7.setBackground(new java.awt.Color(0,204,51));
                btnPindah7.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("8")){
                tw.btn8.setBackground(new java.awt.Color(0,204,51));
                btnPindah8.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("9")){
                tw.btn9.setBackground(new java.awt.Color(0,204,51));
                btnPindah9.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("10")){
                tw.btn10.setBackground(new java.awt.Color(0,204,51));
                btnPindah10.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("11")){
                tw.btn11.setBackground(new java.awt.Color(0,204,51));
                btnPindah11.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("12")){
                tw.btn12.setBackground(new java.awt.Color(0,204,51));
                btnPindah12.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("13")){
                tw.btn13.setBackground(new java.awt.Color(0,204,51));
                btnPindah13.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("14")){
                tw.btn14.setBackground(new java.awt.Color(0,204,51));
                btnPindah14.setBackground(new java.awt.Color(0,204,51));
            }else if(krsAwal.getText().equals("15")){
                tw.btn15.setBackground(new java.awt.Color(0,204,51));
                btnPindah15.setBackground(new java.awt.Color(0,204,51));
            }
            
            
            
            // Untuk set warna kuning
            if(krsSekarang.getText().equals("1")) {
                btnPindah1.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn1.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("1");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("2")){
                btnPindah2.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn2.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("2");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("3")){
                btnPindah3.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn3.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("3");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("4")){
                btnPindah4.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn4.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("4");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("5")){
                btnPindah5.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn5.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("5");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("6")){
                btnPindah6.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn6.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("6");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("7")){
                btnPindah7.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn7.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("7");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("8")){
                btnPindah8.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn8.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("8");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("9")){
                btnPindah9.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn9.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("9");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("10")){
                btnPindah10.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn10.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("10");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("11")){
                btnPindah11.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn11.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("11");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("12")){
                btnPindah12.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn12.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("12");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("13")){
                btnPindah13.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn13.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("13");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("14")){
                btnPindah14.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn14.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("14");
                tw.noReservasi.setText(krsSekarang.getText());
            }else if(krsSekarang.getText().equals("15")){
                btnPindah15.setBackground(new java.awt.Color(247, 252, 26));
                tw.btn15.setBackground(new java.awt.Color(247, 252, 26));
                krsAwal.setText("15");
                tw.noReservasi.setText(krsSekarang.getText());
            }
            String b = krsAwal.getText();
            tw.Namarev.setText(Namacadangan.getText());
            tw.Norev.setText(b);
            this.setVisible(false);
            tw.setVisible(true);
            
        }else if(konfirmasi == JOptionPane.NO_OPTION) {
            krsSekarang.setText("");
            tw.setVisible(false);
        }
        
        
        
    }//GEN-LAST:event_OkepindahActionPerformed

    private void CloserevComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CloserevComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CloserevComponentAdded

    private void CloserevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloserevMouseClicked
       WarungSolo a = new WarungSolo();
       a.setVisible(true);
       this.dispose();
       this.hide();
    }//GEN-LAST:event_CloserevMouseClicked

    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pindah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pindah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pindah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pindah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pindah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closerev;
    public javax.swing.JLabel Namacadangan;
    private javax.swing.JButton Okepindah;
    private javax.swing.JLabel awal;
    public javax.swing.JButton btnPindah1;
    public javax.swing.JButton btnPindah10;
    public javax.swing.JButton btnPindah11;
    public javax.swing.JButton btnPindah12;
    public javax.swing.JButton btnPindah13;
    public javax.swing.JButton btnPindah14;
    public javax.swing.JButton btnPindah15;
    public javax.swing.JButton btnPindah2;
    public javax.swing.JButton btnPindah3;
    public javax.swing.JButton btnPindah4;
    public javax.swing.JButton btnPindah5;
    public javax.swing.JButton btnPindah6;
    public javax.swing.JButton btnPindah7;
    public javax.swing.JButton btnPindah8;
    public javax.swing.JButton btnPindah9;
    public javax.swing.JLabel cadangan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel krsAwal;
    public javax.swing.JLabel krsSekarang;
    private javax.swing.JLabel pindah;
    // End of variables declaration//GEN-END:variables
}
