/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warunginspirasi;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Anas.A
 */
public class TampilanAwal extends javax.swing.JFrame {

    /**
     * Creates new form TampilanAwal
     */
    
    String namaTombol;
    public TampilanAwal() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JLabel();
        btnReservasi = new javax.swing.JLabel();
        btnMenu = new javax.swing.JLabel();
        btnKritik = new javax.swing.JLabel();
        btnTentang = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();
        Mainpanel = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnPesan = new javax.swing.JLabel();
        btnBeranda = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        panelReservasi = new javax.swing.JPanel();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        Namarev = new javax.swing.JTextField();
        btnOkerev = new javax.swing.JLabel();
        Norev = new javax.swing.JLabel();
        btnPindah = new javax.swing.JLabel();
        reservasi = new javax.swing.JLabel();
        panelMakanan = new javax.swing.JPanel();
        makanan = new javax.swing.JLabel();
        panelKritik = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHomeMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        btnReservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reservasi.png"))); // NOI18N
        btnReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReservasiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnReservasiMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReservasiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReservasiMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReservasiMouseEntered(evt);
            }
        });
        getContentPane().add(btnReservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 310, 160, -1));

        btnKritik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kritik saran.png"))); // NOI18N
        btnKritik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKritikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKritikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKritikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKritikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKritikMouseReleased(evt);
            }
        });
        getContentPane().add(btnKritik, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        btnTentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tentang.png"))); // NOI18N
        btnTentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTentangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTentangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTentangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTentangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTentangMouseReleased(evt);
            }
        });
        getContentPane().add(btnTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/keluar.png"))); // NOI18N
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKeluarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKeluarMouseReleased(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/panel.png"))); // NOI18N
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 250, 660));

        Mainpanel.setLayout(new java.awt.CardLayout());

        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pesan sekarang.png"))); // NOI18N
        btnPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPesanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPesanMouseReleased(evt);
            }
        });
        panelHome.add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/beranda.png"))); // NOI18N
        btnBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBerandaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBerandaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBerandaMouseReleased(evt);
            }
        });
        panelHome.add(btnBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 370, 50));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/adminlogin.png"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoginMouseReleased(evt);
            }
        });
        panelHome.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 100, 340, 50));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/menuAwal.png"))); // NOI18N
        panelHome.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Mainpanel.add(panelHome, "card2");

        panelReservasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn11.setBackground(new java.awt.Color(0, 204, 51));
        btn11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn11.setText("11");
        btn11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 523, 130, 80));

        btn12.setBackground(new java.awt.Color(0, 204, 51));
        btn12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn12.setText("12");
        btn12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 523, 140, 80));

        btn13.setBackground(new java.awt.Color(0, 204, 51));
        btn13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn13.setText("13");
        btn13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 523, 140, 80));

        btn14.setBackground(new java.awt.Color(0, 204, 51));
        btn14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn14.setText("14");
        btn14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 523, 140, 80));

        btn15.setBackground(new java.awt.Color(0, 204, 51));
        btn15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn15.setText("15");
        btn15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 523, 130, 80));

        btn6.setBackground(new java.awt.Color(0, 204, 51));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 443, 130, 80));

        btn7.setBackground(new java.awt.Color(0, 204, 51));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 443, 140, 80));

        btn8.setBackground(new java.awt.Color(0, 204, 51));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 443, 140, 80));

        btn9.setBackground(new java.awt.Color(0, 204, 51));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 443, 140, 80));

        btn10.setBackground(new java.awt.Color(0, 204, 51));
        btn10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn10.setText("10");
        btn10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 443, 130, 80));

        btn1.setBackground(new java.awt.Color(0, 204, 51));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 363, 130, 80));

        btn2.setBackground(new java.awt.Color(0, 204, 51));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 363, 140, 80));

        btn3.setBackground(new java.awt.Color(0, 204, 51));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 363, 140, 80));

        btn4.setBackground(new java.awt.Color(0, 204, 51));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 363, 140, 80));

        btn5.setBackground(new java.awt.Color(0, 204, 51));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        panelReservasi.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 363, 130, 80));

        Namarev.setBackground(new java.awt.Color(234, 234, 234));
        Namarev.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        Namarev.setBorder(null);
        panelReservasi.add(Namarev, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 270, 30));

        btnOkerev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ok.png"))); // NOI18N
        btnOkerev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkerevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOkerevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOkerevMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOkerevMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOkerevMouseReleased(evt);
            }
        });
        panelReservasi.add(btnOkerev, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 100, -1));

        Norev.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        panelReservasi.add(Norev, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 50, 40));

        btnPindah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPindah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pindah.png"))); // NOI18N
        btnPindah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPindahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPindahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPindahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPindahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPindahMouseReleased(evt);
            }
        });
        panelReservasi.add(btnPindah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 110, 40));

        reservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/reservasiNew.png"))); // NOI18N
        reservasi.setText("jLabel2");
        reservasi.setMaximumSize(new java.awt.Dimension(684, 636));
        reservasi.setMinimumSize(new java.awt.Dimension(684, 636));
        reservasi.setPreferredSize(new java.awt.Dimension(684, 636));
        panelReservasi.add(reservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 660));

        Mainpanel.add(panelReservasi, "card3");

        panelMakanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        makanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/menuMakanan.png"))); // NOI18N
        makanan.setText("jLabel3");
        panelMakanan.add(makanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Mainpanel.add(panelMakanan, "card4");

        panelKritik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/KritikSaran.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        panelKritik.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        Mainpanel.add(panelKritik, "card5");

        getContentPane().add(Mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 640));

        setSize(new java.awt.Dimension(911, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
//Tombol Home
    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        ImageIcon hm = new ImageIcon(getClass().getResource("/icon/homeputih.png"));
        btnHome.setIcon(hm);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        ImageIcon hm = new ImageIcon(getClass().getResource("/icon/home.png"));
        btnHome.setIcon(hm);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        ImageIcon hm = new ImageIcon(getClass().getResource("/icon/homehitam.png"));
        btnHome.setIcon(hm);
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased
        ImageIcon hm = new ImageIcon(getClass().getResource("/icon/homeputih.png"));
        btnHome.setIcon(hm);
    }//GEN-LAST:event_btnHomeMouseReleased

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // Hapus panel
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        // Tambah panel
        Mainpanel.add(panelHome);
        Mainpanel.repaint();
        Mainpanel.revalidate();
    }//GEN-LAST:event_btnHomeMouseClicked

    
    private void btnReservasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasiMouseEntered
        ImageIcon rs = new ImageIcon(getClass().getResource("/icon/reservasiputih.png"));
        btnReservasi.setIcon(rs);
    }//GEN-LAST:event_btnReservasiMouseEntered

    private void btnReservasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasiMouseExited
        ImageIcon rs = new ImageIcon(getClass().getResource("/icon/reservasi.png"));
        btnReservasi.setIcon(rs);
    }//GEN-LAST:event_btnReservasiMouseExited

    private void btnReservasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasiMousePressed
        ImageIcon rs = new ImageIcon(getClass().getResource("/icon/reservasihitam.png"));
        btnReservasi.setIcon(rs);
    }//GEN-LAST:event_btnReservasiMousePressed

    private void btnReservasiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasiMouseReleased
        ImageIcon rs = new ImageIcon(getClass().getResource("/icon/reservasiputih.png"));
        btnReservasi.setIcon(rs);
    }//GEN-LAST:event_btnReservasiMouseReleased

    private void btnReservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasiMouseClicked
        // Hapus panel
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        // Tambah panel
        Mainpanel.add(panelReservasi);
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        FormReservasi fr = new FormReservasi();
//        ReservasiDesktop.add(fr).setVisible(true);
        
    }//GEN-LAST:event_btnReservasiMouseClicked

    
    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        ImageIcon mn = new ImageIcon(getClass().getResource("/icon/menuputih.png"));
        btnMenu.setIcon(mn);
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        ImageIcon mn = new ImageIcon(getClass().getResource("/icon/menuhitam.png"));
        btnMenu.setIcon(mn);
    }//GEN-LAST:event_btnMenuMousePressed

    private void btnMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseReleased
        ImageIcon mn = new ImageIcon(getClass().getResource("/icon/menuputih.png"));
        btnMenu.setIcon(mn);
    }//GEN-LAST:event_btnMenuMouseReleased

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // Hapus panel
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        // Tambah panel
        Mainpanel.add(panelMakanan);
        Mainpanel.repaint();
        Mainpanel.revalidate();
    }//GEN-LAST:event_btnMenuMouseClicked

    
    private void btnKritikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKritikMouseEntered
        ImageIcon ks = new ImageIcon(getClass().getResource("/icon/kritiksaranputih.png"));
        btnKritik.setIcon(ks);
    }//GEN-LAST:event_btnKritikMouseEntered

    private void btnKritikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKritikMouseExited
        ImageIcon ks = new ImageIcon(getClass().getResource("/icon/kritik saran.png"));
        btnKritik.setIcon(ks);
    }//GEN-LAST:event_btnKritikMouseExited

    private void btnKritikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKritikMousePressed
        ImageIcon ks = new ImageIcon(getClass().getResource("/icon/kritiksaranhitam.png"));
        btnKritik.setIcon(ks);
    }//GEN-LAST:event_btnKritikMousePressed

    private void btnKritikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKritikMouseReleased
        ImageIcon ks = new ImageIcon(getClass().getResource("/icon/kritiksaranputih.png"));
        btnKritik.setIcon(ks);
    }//GEN-LAST:event_btnKritikMouseReleased

    private void btnKritikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKritikMouseClicked
        // Hapus panel
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        // Tambah panel
        Mainpanel.add(panelKritik);
        Mainpanel.repaint();
        Mainpanel.revalidate();
    }//GEN-LAST:event_btnKritikMouseClicked

    
    private void btnTentangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangMouseEntered
        ImageIcon tn = new ImageIcon(getClass().getResource("/icon/tentangputih.png"));
        btnTentang.setIcon(tn);
    }//GEN-LAST:event_btnTentangMouseEntered

    private void btnTentangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangMouseExited
        ImageIcon tn = new ImageIcon(getClass().getResource("/icon/tentang.png"));
        btnTentang.setIcon(tn);
    }//GEN-LAST:event_btnTentangMouseExited

    private void btnTentangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangMousePressed
        ImageIcon tn = new ImageIcon(getClass().getResource("/icon/tentanghitam.png"));
        btnTentang.setIcon(tn);
    }//GEN-LAST:event_btnTentangMousePressed

    private void btnTentangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangMouseReleased
        ImageIcon tn = new ImageIcon(getClass().getResource("/icon/tentangputih.png"));
        btnTentang.setIcon(tn);
    }//GEN-LAST:event_btnTentangMouseReleased

    private void btnTentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangMouseClicked
        new PopupTentang().setVisible(true);
    }//GEN-LAST:event_btnTentangMouseClicked

    
    private void btnKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseEntered
        ImageIcon kl = new ImageIcon(getClass().getResource("/icon/keluarputih.png"));
        btnKeluar.setIcon(kl);
    }//GEN-LAST:event_btnKeluarMouseEntered

    private void btnKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseExited
        ImageIcon kl = new ImageIcon(getClass().getResource("/icon/keluar.png"));
        btnKeluar.setIcon(kl);
    }//GEN-LAST:event_btnKeluarMouseExited

    private void btnKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMousePressed
        ImageIcon kl = new ImageIcon(getClass().getResource("/icon/keluarhitam.png"));
        btnKeluar.setIcon(kl);
    }//GEN-LAST:event_btnKeluarMousePressed

    private void btnKeluarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseReleased
        ImageIcon kl = new ImageIcon(getClass().getResource("/icon/keluarputih.png"));
        btnKeluar.setIcon(kl);
    }//GEN-LAST:event_btnKeluarMouseReleased

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnKeluarMouseClicked

    
    
//Bagian Menu Home
    private void btnPesanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesanMouseEntered
        ImageIcon ps = new ImageIcon(getClass().getResource("/icon/pesan sekarang putih.png"));
        btnPesan.setIcon(ps);
    }//GEN-LAST:event_btnPesanMouseEntered

    private void btnPesanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesanMouseExited
        ImageIcon ps = new ImageIcon(getClass().getResource("/icon/pesan sekarang.png"));
        btnPesan.setIcon(ps);
    }//GEN-LAST:event_btnPesanMouseExited

    private void btnPesanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesanMousePressed
        ImageIcon ps = new ImageIcon(getClass().getResource("/icon/pesan sekarang hitam.png"));
        btnPesan.setIcon(ps);
    }//GEN-LAST:event_btnPesanMousePressed

    private void btnPesanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesanMouseReleased
        ImageIcon ps = new ImageIcon(getClass().getResource("/icon/pesan sekarang putih.png"));
        btnPesan.setIcon(ps);
    }//GEN-LAST:event_btnPesanMouseReleased

    private void btnPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesanMouseClicked
        // Hapus panel
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        // Tambah panel
        Mainpanel.add(panelReservasi);
        Mainpanel.repaint();
        Mainpanel.revalidate();
    }//GEN-LAST:event_btnPesanMouseClicked

    
    private void btnBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseEntered
        ImageIcon al = new ImageIcon(getClass().getResource("/icon/berandaputih.png"));
        btnBeranda.setIcon(al);
    }//GEN-LAST:event_btnBerandaMouseEntered

    private void btnBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseExited
        ImageIcon al = new ImageIcon(getClass().getResource("/icon/beranda.png"));
        btnBeranda.setIcon(al);
    }//GEN-LAST:event_btnBerandaMouseExited

    private void btnBerandaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMousePressed
        ImageIcon al = new ImageIcon(getClass().getResource("/icon/berandahitam.png"));
        btnBeranda.setIcon(al);
    }//GEN-LAST:event_btnBerandaMousePressed

    private void btnBerandaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseReleased
        ImageIcon al = new ImageIcon(getClass().getResource("/icon/berandaputih.png"));
        btnBeranda.setIcon(al);
    }//GEN-LAST:event_btnBerandaMouseReleased

    private void btnBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBerandaMouseClicked
        // Hapus panel
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        // Tambah panel
        Mainpanel.add(panelHome);
        Mainpanel.repaint();
        Mainpanel.revalidate();
    }//GEN-LAST:event_btnBerandaMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        ImageIcon lg = new ImageIcon(getClass().getResource("/icon/adminloginputih.png"));
        btnLogin.setIcon(lg);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        ImageIcon lg = new ImageIcon(getClass().getResource("/icon/adminlogin.png"));
        btnLogin.setIcon(lg);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
        ImageIcon lg = new ImageIcon(getClass().getResource("/icon/adminloginhitam.png"));
        btnLogin.setIcon(lg);
    }//GEN-LAST:event_btnLoginMousePressed

    private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
        ImageIcon lg = new ImageIcon(getClass().getResource("/icon/adminloginputih.png"));
        btnLogin.setIcon(lg);
    }//GEN-LAST:event_btnLoginMouseReleased

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        FormLogin fl = new FormLogin();
        fl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        Norev.setText("15");
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        Norev.setText("14");
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        Norev.setText("13");
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        Norev.setText("12");
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        Norev.setText("11");
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        Norev.setText("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        Norev.setText("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        Norev.setText("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        Norev.setText("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        Norev.setText("10");
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        Norev.setText("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        Norev.setText("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        Norev.setText("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        Norev.setText("2");
    }//GEN-LAST:event_btn2ActionPerformed

// Tombol pesanan tempaT duduk di menu reservasi
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        Norev.setText("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnOkerevMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMouseReleased
        ImageIcon bo = new ImageIcon(getClass().getResource("/icon/okputih.png"));
        btnOkerev.setIcon(bo);
    }//GEN-LAST:event_btnOkerevMouseReleased

    private void btnOkerevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMousePressed
        ImageIcon bo = new ImageIcon(getClass().getResource("/icon/okhitam.png"));
        btnOkerev.setIcon(bo);
    }//GEN-LAST:event_btnOkerevMousePressed

    private void btnOkerevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMouseExited
        ImageIcon bo = new ImageIcon(getClass().getResource("/icon/ok.png"));
        btnOkerev.setIcon(bo);
    }//GEN-LAST:event_btnOkerevMouseExited

// tombol oke di menu Reservasi
    private void btnOkerevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMouseEntered
        ImageIcon bo = new ImageIcon(getClass().getResource("/icon/okputih.png"));
        btnOkerev.setIcon(bo);
    }//GEN-LAST:event_btnOkerevMouseEntered

// Tombol Oke di Menu Reservasi
    private void btnOkerevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkerevMouseClicked

        String a = Namarev.getText();
        Namarev.setText(a);

        if(Namarev.getText().isEmpty() && Norev.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama dan Reservasi harus diisi");
        }else if(Namarev.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong");
        }else if(Norev.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nomor Reservasi tidak boleh kosong");
        }else if(Norev.getText().equalsIgnoreCase("1")) {
            btn1.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("2")){
            btn2.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("3")){
            btn3.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("4")){
            btn4.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("5")){
            btn5.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("6")){
            btn6.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("7")){
            btn7.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("8")){
            btn8.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("9")){
            btn9.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("10")){
            btn10.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("11")){
            btn11.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("12")){
            btn12.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("13")){
            btn13.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("14")){
            btn14.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }else if(Norev.getText().equalsIgnoreCase("15")){
            btn15.setBackground(new java.awt.Color(247, 252, 26));
            JOptionPane.showMessageDialog(this, "Reservasi berhasil silahkan memesan menu yang tersedia untuk menggunakan tempat");
        }

    }//GEN-LAST:event_btnOkerevMouseClicked

    private void btnPindahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMouseReleased
        ImageIcon bp = new ImageIcon(getClass().getResource("/icon/pindahputih.png"));
        btnPindah.setIcon(bp);
    }//GEN-LAST:event_btnPindahMouseReleased

    private void btnPindahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMousePressed
        ImageIcon bp = new ImageIcon(getClass().getResource("/icon/pindahhitam.png"));
        btnPindah.setIcon(bp);
    }//GEN-LAST:event_btnPindahMousePressed

    private void btnPindahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMouseExited
        ImageIcon bp = new ImageIcon(getClass().getResource("/icon/pindah.png"));
        btnPindah.setIcon(bp);
    }//GEN-LAST:event_btnPindahMouseExited

// Button Pindah menu Reservasi
    private void btnPindahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMouseEntered
        ImageIcon bp = new ImageIcon(getClass().getResource("/icon/pindahputih.png"));
        btnPindah.setIcon(bp);
    }//GEN-LAST:event_btnPindahMouseEntered

    private void btnPindahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPindahMouseClicked
        Pindah pd = new Pindah();
        pd.setVisible(true);
        this.setVisible(false);

        String b = Norev.getText();
        pd.krsAwal.setText(b);
        String a = Namarev.getText();
                pd.Namacadangan.setText(a);
                pd.Namacadangan.hide();

        if(Norev.getText().equalsIgnoreCase("1")) {
            pd.btnPindah1.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("2")) {
            pd.btnPindah2.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("3")) {
            pd.btnPindah3.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("4")) {
            pd.btnPindah4.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("5")) {
            pd.btnPindah5.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("6")) {
            pd.btnPindah6.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("7")) {
            pd.btnPindah7.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("8")) {
            pd.btnPindah8.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("9")) {
            pd.btnPindah9.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("10")) {
            pd.btnPindah10.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("11")) {
            pd.btnPindah11.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("12")) {
            pd.btnPindah12.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("13")) {
            pd.btnPindah13.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("14")) {
            pd.btnPindah14.setBackground(new java.awt.Color(247, 252, 26));
        }else if(Norev.getText().equalsIgnoreCase("15")) {
            pd.btnPindah15.setBackground(new java.awt.Color(247, 252, 26));
        }

    }//GEN-LAST:event_btnPindahMouseClicked

    
// btn Menu ini menyendiri karena tadi sempat error
    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        ImageIcon mn = new ImageIcon(getClass().getResource("/icon/menu.png"));
        btnMenu.setIcon(mn);
    }//GEN-LAST:event_btnMenuMouseExited

    

    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanAwal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mainpanel;
    public javax.swing.JTextField Namarev;
    public javax.swing.JLabel Norev;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn10;
    public javax.swing.JButton btn11;
    public javax.swing.JButton btn12;
    public javax.swing.JButton btn13;
    public javax.swing.JButton btn14;
    public javax.swing.JButton btn15;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    private javax.swing.JLabel btnBeranda;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnKritik;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnMenu;
    public javax.swing.JLabel btnOkerev;
    private javax.swing.JLabel btnPesan;
    private javax.swing.JLabel btnPindah;
    private javax.swing.JLabel btnReservasi;
    private javax.swing.JLabel btnTentang;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel makanan;
    private javax.swing.JLabel panel;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelKritik;
    private javax.swing.JPanel panelMakanan;
    protected javax.swing.JPanel panelReservasi;
    private javax.swing.JLabel reservasi;
    // End of variables declaration//GEN-END:variables
}
